export const capitalsList = {
    amsterdam: '../images/CapitalPhotos/amsterdam.jpg',
    'andorra la vella': '../images/CapitalPhotos/andorralavella.jpg',
    athens: '../images/CapitalPhotos/athens.jpg',
    belgrade: '../images/CapitalPhotos/belgrade.jpg',
    berlin: '../images/CapitalPhotos/berlin.jpg',
    bern: '../images/CapitalPhotos/bern.jpg',
    bratislava: '../images/CapitalPhotos/bratislava.jpg',
    brussels: '../images/CapitalPhotos/brussels.jpg',
    bucharest: '../images/CapitalPhotos/bucharest.jpg',
    budapest: '../images/CapitalPhotos/budapest.jpg',
    chisinau: '../images/CapitalPhotos/chisinau.jpg',
    copenhagen: '../images/CapitalPhotos/copenhagen.jpg',
    dublin: '../images/CapitalPhotos/dublin.jpg',
    helsinki: '../images/CapitalPhotos/helsinki.jpg',
    kiev: '../images/CapitalPhotos/kiev.jpg',
    lisbon: '../images/CapitalPhotos/lisbon.jpg',
    ljubljana: '../images/CapitalPhotos/ljubljana.jpg',
    london: '../images/CapitalPhotos/london.jpg',
    luxembourg: '../images/CapitalPhotos/luxembourg.jpg',
    madrid: '../images/CapitalPhotos/madrid.jpg',
    minsk: '../images/CapitalPhotos/minsk.jpg',
    monaco: '../images/CapitalPhotos/monaco.jpg',
    moscow: '../images/CapitalPhotos/moscow.jpg',
    nicosia: '../images/CapitalPhotos/nicosia.jpg',
    nuuk: '../images/CapitalPhotos/nuuk.jpg',
    oslo: '../images/CapitalPhotos/oslo.jpg',
    paris: '../images/CapitalPhotos/paris.jpg',
    podgorica: '../images/CapitalPhotos/podgorica.jpg',
    prague: '../images/CapitalPhotos/prague.jpg',
    reykjavik: '../images/CapitalPhotos/reykjavik.jpg',
    riga: '../images/CapitalPhotos/riga.jpg',
    rome: '../images/CapitalPhotos/rome.jpg',
    'san marino': '../images/CapitalPhotos/sanmarino.jpg',
    sarajevo: '../images/CapitalPhotos/sarajevo.jpg',
    skopje: '../images/CapitalPhotos/skopje.jpg',
    sofia: '../images/CapitalPhotos/sofia.jpg',
    stockholm: '../images/CapitalPhotos/stockholm.jpg',
    tallinn: '../images/CapitalPhotos/tallinn.jpg',
    tirana: '../images/CapitalPhotos/tirana.jpg',
    vaduz: '../images/CapitalPhotos/vaduz.jpg',
    valletta: '../images/CapitalPhotos/valletta.jpg',
    'vatican city': '../images/CapitalPhotos/vaticancity.jpg',
    vienna: '../images/CapitalPhotos/vienna.jpg',
    warsaw: '../images/CapitalPhotos/warsaw.jpg',
    zagreb: '../images/CapitalPhotos/zagreb.jpg'
}